name: rebase-test
on:
  issue_comment:
    types: [created]

jobs:
  try_comment:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN_PRIVATE }}
      - name: rebase
        uses: MobileheadHolding/github-action-rebase@master
        with:
          giphy-key: ${{ secrets.GIPHY_API_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}