name: rebase-test
on:
  issue_comment:
    types: [created]

jobs:
  try_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: rebase
        uses: MobileheadHolding/github-action-rebase@master
        with:
          giphy-key: ${{ secrets.GIPHY_API_KEY }}
        env:
          GITHUB_USER_NAME: "MobileheadBot"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_PRIVATE }}